### ISSUE TITLE
When a key is passed to Encrypt action, a new key should not be created. Output needs to be input key. 

### ISSUE THREAD

**Issue by pranavred** [blue-prism/utility-encryption#2]
// initalize output variables
encryptedData = String.Empty;
newKey = String.Empty;

string publicKeyString = string.Empty;
string privateKeyString = string.Empty;

using (var rsaCryptoServiceProvider = new RSACryptoServiceProvider(2048)) //2048 - Key length
{
	if (!IsKeyProvided(inputKey)) // if inputKey is blank, use a new key
	{ 
		var privateKey = rsaCryptoServiceProvider.ExportParameters(true); //Generating private key
		var publicKey = rsaCryptoServiceProvider.ExportParameters(false); //Generating private key
		
		publicKeyString = GetRSAKeyString(publicKey);
		privateKeyString = GetRSAKeyString(privateKey);
	}
	**else 
	{
		publicKeyString = inputKey;
	}**

	var bytesToEncrypt = Encoding.UTF8.GetBytes(inputData);

	try
	{               
		rsaCryptoServiceProvider.FromXmlString(publicKeyString);
		
		var encryptedBytes = rsaCryptoServiceProvider.Encrypt(bytesToEncrypt, true);
		encryptedData = Convert.ToBase64String(encryptedBytes);
		newKey = privateKeyString;

	}
	catch (Exception ex)
	{
		throw ex;
	}
	finally
	{
		rsaCryptoServiceProvider.PersistKeyInCsp = false;
	}
}

**Comment by charlie-kovacs** [comment]
Hi Pranav,

Good catch. I agree with the `else` statement you are proposing. My tests passed and I pushed a new version. Try the latest from the master branch here and see if you find this issue resolved as well.

I also moved `newKey = privateKeyString;` within the `if` block. This makes the behavior congruent with the other actions in this VBO. By that I mean, the `New Key` output parameter will _only_ be populated if no key is provided in the input parameters. This will eliminate any ambiguity as to whether this code stage is using the supplied input key or generating a new one.

Closing the issue, but do let me know if you find anything amiss.

Regards
